ci: Enable initial unit tests and remove auto-formatting in PRs (#10)
* Remove autoformatting

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Test isort lint checking

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Test fixing isort

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Install lint dependencies from requirements_test.txt

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Add pylint to requirements_test.txt

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Add flake8 to requirements_test.txt

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Test black formatting failure

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Test black format failiure

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Remove example.py

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Remove directories from being excluded for formatting checks

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Add initial test

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Add initial test placeholder

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Always require test comment to run CI tests

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix lint errors

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix workflow

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix workflow

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix test template

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Use test template

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix test path

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix path ref

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix test

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Fix test template ref

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

* Do not require test comment for trusted devs

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

---------

Signed-off-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/actions/test-template/action.yml b/.github/actions/test-template/action.yml
--- a/.github/actions/test-template/action.yml
+++ b/.github/actions/test-template/action.yml
@@ -11,73 +11,241 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-name: ~Build container template
-on:
-  workflow_call:
-    inputs:
-      image-name:
-        required: true
-        type: string
-        description: "The name of the image to build"
-      dockerfile:
-        required: true
-        type: string
-      runner:
-        required: false
-        default: linux-amd64-gpu-rtxa6000-latest-2-nemo
-        type: string
-        description: "The runner to use for the build"
-    secrets:
-      AZURE_CLIENT_ID:
-        required: true
-      AZURE_TENANT_ID:
-        required: true
-      AZURE_SUBSCRIPTION_ID:
-        required: true
+name: "Test Template"
+description: "Template for running NeMo tests in a containerized environment"
 
-jobs:
-  pre-flight:
-    runs-on: ubuntu-latest
-    outputs:
-      cache-from: ${{ steps.cache-from.outputs.LAST_PRS }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+inputs:
+  runner:
+    description: "Runner to use for test"
+    required: true
+  timeout:
+    description: "Max runtime of test in minutes"
+    required: false
+    default: "10"
+  script:
+    description: "Test script to execute"
+    required: true
+  is_optional:
+    description: "Failure will cancel all other tests if set to true"
+    required: false
+    default: "false"
+  is_unit_test:
+    description: "Upload coverage as unit test"
+    required: false
+    default: "false"
+  image:
+    description: "Image to use for test"
+    required: false
+    default: "nemo_lm"
+  cpu-only:
+    description: "Run tests on CPU only"
+    required: false
+    default: "false"
+  azure-client-id:
+    description: "Azure Client ID"
+    required: true
+  azure-tenant-id:
+    description: "Azure Tenant ID"
+    required: true
+  azure-subscription-id:
+    description: "Azure Subscription ID"
+    required: true
+  has-azure-credentials:
+    description: "Has Azure credentials"
+    required: false
+    default: "false"
 
-      - name: Get last merged PR
-        id: cache-from
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          LAST_PRS=$(gh api graphql -f query='
-            query {
-              repository(owner: "NVIDIA", name: "NeMo-LM") {
-                pullRequests(states: MERGED, first: 100, orderBy: {field: UPDATED_AT, direction: DESC}) {
-                  nodes {
-                    number
-                  }
-                }
-              }
-            }' | jq -r '.data.repository.pullRequests.nodes[].number' | while read -r number; do
-              echo "nemoci.azurecr.io/${{ inputs.image-name }}-buildcache:$number"
-            done)
+runs:
+  using: "composite"
+  steps:
+    - name: Install Azure CLI
+      if: ${{ inputs.has-azure-credentials == 'true' }}
+      shell: bash
+      run: |
+        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
 
-          echo "LAST_PRS<<EOF" >> $GITHUB_OUTPUT
-          echo "$LAST_PRS" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+    - name: Azure Login
+      if: ${{ inputs.has-azure-credentials == 'true' }}
+      uses: azure/login@v2
+      with:
+        client-id: ${{ inputs.azure-client-id }}
+        tenant-id: ${{ inputs.azure-tenant-id }}
+        subscription-id: ${{ inputs.azure-subscription-id }}
 
-  build:
-    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_build_container.yml@v0.29.0
-    needs: [pre-flight]
-    with:
-      image-name: ${{ inputs.image-name }}
-      dockerfile: ${{ inputs.dockerfile }}
-      image-label: nemo-core
-      prune-filter-timerange: 24h
-      use-inline-cache: false
-      runner: ${{ inputs.runner }}
-      has-azure-credentials: true
-    secrets:
-      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+    - name: Azure ACR Login
+      if: ${{ inputs.has-azure-credentials == 'true' }}
+      shell: bash
+      run: |
+        az acr login --name nemoci
+
+    - name: Azure Fileshare
+      if: ${{ inputs.has-azure-credentials == 'true' && inputs.is_unit_test == 'false' }}
+      shell: bash
+      id: azure-fileshare
+      run: |
+        sudo apt update
+        sudo apt install -y cifs-utils
+
+        RESOURCE_GROUP_NAME="azure-gpu-vm-runner_group"
+        STORAGE_ACCOUNT_NAME="nemocistorageaccount2"
+        FILE_SHARE_NAME="fileshare"
+
+        MNT_ROOT="/media"
+        MNT_PATH="$MNT_ROOT/$STORAGE_ACCOUNT_NAME/$FILE_SHARE_NAME"
+
+        echo "MNT_PATH=$MNT_PATH" | tee -a "$GITHUB_OUTPUT"
+
+        sudo mkdir -p $MNT_PATH
+
+        # Create a folder to store the credentials for this storage account and
+        # any other that you might set up.
+        CREDENTIAL_ROOT="/etc/smbcredentials"
+        sudo mkdir -p "/etc/smbcredentials"
+
+        # Get the storage account key for the indicated storage account.
+        # You must be logged in with az login and your user identity must have
+        # permissions to list the storage account keys for this command to work.
+        STORAGE_ACCOUNT_KEY=$(az storage account keys list \
+            --resource-group $RESOURCE_GROUP_NAME \
+            --account-name $STORAGE_ACCOUNT_NAME \
+            --query "[0].value" --output tsv | tr -d '"')
+
+        # Create the credential file for this individual storage account
+        SMB_CREDENTIAL_FILE="$CREDENTIAL_ROOT/$STORAGE_ACCOUNT_NAME.cred"
+        if [ ! -f $SMB_CREDENTIAL_FILE ]; then
+            echo "username=$STORAGE_ACCOUNT_NAME" | sudo tee $SMB_CREDENTIAL_FILE > /dev/null
+            echo "password=$STORAGE_ACCOUNT_KEY" | sudo tee -a $SMB_CREDENTIAL_FILE > /dev/null
+        else
+            echo "The credential file $SMB_CREDENTIAL_FILE already exists, and was not modified."
+        fi
+
+        # Change permissions on the credential file so only root can read or modify the password file.
+        sudo chmod 600 $SMB_CREDENTIAL_FILE
+
+        # This command assumes you have logged in with az login
+        HTTP_ENDPOINT=$(az storage account show --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --query "primaryEndpoints.file" --output tsv | tr -d '"')
+        SMB_PATH=$(echo $HTTP_ENDPOINT | cut -c7-${#HTTP_ENDPOINT})$FILE_SHARE_NAME
+
+        STORAGE_ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query "[0].value" --output tsv | tr -d '"')
+
+        sudo mount -t cifs $SMB_PATH $MNT_PATH -o credentials=$SMB_CREDENTIAL_FILE,serverino,nosharesock,actimeo=30,mfsymlinks
+
+        ls -al $MNT_PATH/TestData
+
+    - name: Docker pull image
+      shell: bash
+      run: |
+        docker pull nemoci.azurecr.io/${{ inputs.image }}:${{ github.run_id }}
+
+    - name: Checkout repository
+      uses: actions/checkout@v2
+      with:
+        path: NeMo-LM
+
+    - name: Start container
+      shell: bash
+      run: |
+        MNT_PATH=${{ steps.azure-fileshare.outputs.mnt_path }}
+
+        ARG=("")
+        if [[ "${{ inputs.cpu-only }}" == "false" ]]; then
+          ARG=("--runtime=nvidia --gpus all")
+        fi
+
+        cmd=$(cat <<RUN_TEST_EOF
+        #!/bin/bash
+        docker container rm -f nemo_container_${{ github.run_id }} || true
+        docker run \
+          --rm \
+          -d \
+          --name nemo_container_${{ github.run_id }} ${ARG[@]} \
+          --shm-size=64g \
+          --env TRANSFORMERS_OFFLINE=0 \
+          --env HYDRA_FULL_ERROR=1 \
+          --env HF_HOME=/home/TestData/HF_HOME \
+          --env RUN_ID=${{ github.run_id }} \
+          --volume $(pwd)/NeMo-LM:/workspace \
+          --volume $MNT_PATH/TestData:/home/TestData \
+          nemoci.azurecr.io/${{ inputs.image }}:${{ github.run_id }} \
+          bash -c "sleep $(( ${{ inputs.timeout }} * 60 + 60 ))"
+        RUN_TEST_EOF
+        )
+
+        echo "$cmd" | tee "retry_job.sh"
+        bash retry_job.sh
+        docker exec -t nemo_container_${{ github.run_id }} bash -c 'pip install -e .'
+
+    - name: Create run-script
+      id: create
+      shell: bash
+      run: |
+        COVERAGE_PREFIX=$([[ "${{ inputs.is_unit_test }}" == "true" ]] && echo "unit-test" || echo "e2e")
+        echo "coverage-prefix=$COVERAGE_PREFIX" | tee -a "$GITHUB_OUTPUT"
+
+        cmd=$(cat <<RUN_TEST_EOF
+        #!/bin/bash
+
+        (
+          set -e
+
+          docker exec -t nemo_container_${{ github.run_id }} bash -c '\
+            bash tests/${{ inputs.is_unit_test == 'true' && 'unit_tests' || 'functional_tests' }}/${{ inputs.script }}.sh && \
+            echo "Finished successfully." || echo "Did not finish."'
+        ) 2>&1 | tee err.log
+
+        RUN_TEST_EOF
+        )
+
+        echo "timeout_in_seconds=$(( ${{ inputs.timeout }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
+        echo "$cmd" | tee "job.sh"
+
+    - name: Run main script
+      uses: nick-fields/retry@v3
+      with:
+        timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
+        max_attempts: 3
+        shell: bash
+        retry_on: timeout
+        command: /bin/bash job.sh
+        on_retry_command: /bin/bash retry_job.sh
+
+    - name: Check result
+      id: check
+      shell: bash
+      run: |
+        docker exec nemo_container_${{ github.run_id }} coverage combine || true
+        docker exec nemo_container_${{ github.run_id }} coverage xml
+        docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage .coverage
+        docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml coverage.xml
+
+        coverage_report=coverage-${{ steps.create.outputs.coverage-prefix }}-${{ github.run_id }}-$(uuidgen)
+        echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
+
+        IS_SUCCESS=$(tail -n 1 err.log | grep -q "Finished successfully." && echo "true" || echo "false")
+
+        if [[ "$IS_SUCCESS" == "false" && "${{ inputs.is_optional }}" == "true" ]]; then
+          echo "::warning:: Test failed, but displayed as successful because it is marked as optional."
+          IS_SUCCESS=true
+        fi
+
+        if [[ "$IS_SUCCESS" == "false" ]]; then
+          echo Test did not finish successfully.
+          exit 1
+        fi
+
+        exit $EXIT_CODE
+
+    - name: Test coverage
+      shell: bash -x -e -u -o pipefail {0}
+      run: |
+        docker exec -t nemo_container_${{ github.run_id }} coverage report -i
+
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v4
+      if: ${{ steps.check.outputs.coverage_report != 'none' }}
+      with:
+        name: ${{ steps.check.outputs.coverage_report }}
+        path: |
+          coverage.xml
+          .coverage
+        include-hidden-files: true
